version: '3.9'

services:
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile

    nginx:
        image: nginx:1.21-alpine
        depends_on:
            - php-fpm
